python3 train.py \
  --model_name_or_path bert-base-uncased \
  --config_name bert-base-uncased \
  --output_dir ./checkpoints/esnli-highlight \
  --train_file ./data/esnli/esnli.train.sent_highlight.contradiction.jsonl \
  --eval_file ./data/esnli/esnli.dev.sent_highlight.contradiction.jsonl \
  --per_device_train_batch_size 8 \
  --max_steps 12500 \
  --save_steps 2500 \
  --eval_steps 2500 \
  --max_seq_length 256 \
  --evaluation_strategy 'steps'\
  --evaluate_during_training \
  --do_train \
  --do_eval
